[package]
name = "hex2d"
version = "0.1.0"
authors = [ "Dawid Ciężarkiewicz <dpc@dpc.pw>" ]
description = "Helper library for working with 2d hex-grid maps"
documentation = "http://dpc.github.io/hex2d-rs/"
repository = "https://github.com/dpc/hex2d-rs"
homepage = "https://github.com/dpc/hex2d-rs"
readme = "README.md"
keywords = ["game", "map", "hex", "hexagonal", "coordinate"]
license = "MIT"

[lib]
name = "hex2d"
path = "src/lib.rs"

[features]
default = ["serde-serde"]
serde-serde = ["serde", "serde_derive"]
rustc = ["rustc-serialize"]

[dependencies]
num = "*"
rand = "*"
serde = {version="1.0.9",optional=true}
serde_derive = {version="1.0.9", optional=true}
rustc-serialize = {version="*", optional=true}
